### ISSUE TITLE
attempted relative import beyond top-level package

### ISSUE THREAD

**Issue by danmoser** [gLENTNER/SLiPy#1]
Hi there! I'm cloned the repo this late August, and I'm unable to run the documentation examples. I'm running Python 3.7.6.

The first problem is when importing: `No module named 'slipy'`. However `import SLiPy` works.

The major problem is when using `from SLiPy import Spectrum, Plot, Profile`, I get
```
from SLiPy import Spectrum, Plot, Profile
(...)
~/soft/SLiPy/SLiPy/Spectrum.py in <module>

---> 13 from .. import SlipyError
(...)
ValueError: attempted relative import beyond top-level package```

**Comment by danmoser** [comment]
My bad... Wrong path in `PYTHONPATH`

**Comment by glentner** [comment]
No worries. Glad someone is making use of these tools after all these years.
